### PR TITLE
refactoring: notifications

### PR DESCRIPTION
**Pull request by shoom3301**
## MERGE ONLY AFTER KNOWLEDGE SHARING SESSION!!!

Addressed all comments from the previous PRs with notifications changes.
Mostly renamed routes and adjusted collections flags (`required`, `draftAndPublish`, etc.)

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Thank you!

Will you also send a PR to `bff` to adjust to these changes?

**Review by anxolin — APPROVED** [review]
Looks great! thanks for addressing them

**Review by alfetopito — APPROVED** [review]

**Comment by anxolin** [comment]
This PR needs to go coordinated now with CoW Swap?

**Comment by shoom3301** [comment]
@anxolin I kept the old route for backward-compatibility

**Pull request merged**
